receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  datadog:
    api:
      key: ${DATADOG_API_KEY}

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
